name: Run Percy visual tests

on:
  workflow_call:
    inputs:
      default-branch:
        description: 'Default branch of the repository'
        required: false
        type: string
        default: master

jobs:
  percy:
    runs-on: ${{ vars.RUNS_ON }}
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run Percy
        run: npx percy exec -- cypress run --config baseUrl=${{ vars.FRONTENDS_URL }} # Replace static url with secret later
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
